### ISSUE TITLE
Less strict license?

### ISSUE THREAD

**Issue by nrenner** [plepe/overpass-layer#1]
The GPL license of this and the overpass-frontend project prevents us from using them in our MIT-licensed project ([brouter-web](https://github.com/nrenner/brouter-web)).

Which is a pity, as this seems to be the most advanced and best maintained Overpass API plugin for Leaflet.

In case you don't have strong opinions about strict copyleft, would it be an option to switch both projects to a more permissive license, that allows to include libraries without the same license restriction? Like [LGPL](https://choosealicense.com/licenses/lgpl-3.0/) or even [MIT](https://choosealicense.com/licenses/mit/), which seems to be the most used license for Leaflet plugins and other JS libs (e.g. see our [credits list](https://github.com/nrenner/brouter-web#credits-and-licenses)).

**Comment by plepe** [comment]
Hi! I already noticed your comment from yesterday (Saturday?). I been thinking about this, and I think I should really choose a different license. I guess, MIT should be fine?

**Comment by plepe** [comment]
I already started to change, but there are some dependencies which I also have to change:
- https://github.com/plepe/boundingbox/
- ...

**Comment by nrenner** [comment]
>  I guess, MIT should be fine?

MIT would be great.

**Comment by plepe** [comment]
it is done. (500f49fb8648fd937d2861fd6850c9d48ba07a07)
